language: rust
sudo: required
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo clippy --all -- -D warnings
  - cargo test --verbose
