language: rust
sudo: required
rust:
  - 1.36.0
  - 1.39.0
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo clippy --all -- -D warnings
  - cargo test --no-default-features --verbose
  - cargo test --verbose
