language: rust
sudo: required
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo clippy --all -- -D warnings
  - cargo fmt --all -- --check
  - cargo test --verbose
